### ISSUE TITLE
Permission policy for codesource == null

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#117]
#### 1. What should be the permission policy for codesource == null

Granting permissions for Properties("*", "read") seems to be enough for now.

**Comment by hrj** [comment]
The permission problem is evident in this test: https://uprootlabs.github.io/gngrTestCases/test-case/stack-trace/test.html

It fails with this exception:
```
access: access denied ("java.util.PropertyPermission" "rhino.stack.style" "read")
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:462)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1294)
	at java.lang.System.getProperty(System.java:717)
	at org.mozilla.javascript.RhinoException.<clinit>(RhinoException.java:434)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1018)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.lobobrowser.html.js.SecurityControllerImpl.lambda$0(SecurityControllerImpl.java:56)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lobobrowser.html.js.SecurityControllerImpl.callWithDomain(SecurityControllerImpl.java:59)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:802)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.lobobrowser.html.js.Executor.executeFunction(Executor.java:97)
	at org.lobobrowser.html.js.Executor.executeFunction(Executor.java:69)
	at org.lobobrowser.html.js.Window$7.run(Window.java:1513)
	at org.lobobrowser.html.js.Window$JSRunnableTask.run(Window.java:273)
	at org.lobobrowser.html.js.Window$JSScheduler$1.run(Window.java:374)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lobobrowser.html.js.Window$JSScheduler.run(Window.java:380)
access: access allowed ("java.security.SecurityPermission" "getPolicy")
access: domain that failed ProtectionDomain  null
 null
 <no principals>
 null
```

**Comment by hrj** [comment]
The reason for the denied permission might be this: https://github.com/mozilla/rhino/blob/0ce17ecd3cb466d25f8d68b8f061ad23c77e8712/src/org/mozilla/javascript/SecurityUtilities.java

It returns a `null` ProtectionDomain when the SecurityManager is not an instance of RhinoSecurityManager.
