### ISSUE TITLE
SSLHandshakeException when connecting to unsplash.com

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#129]
Can be reproduced with one line of Java code:

```
new java.net.URL("https://unsplash.com/").getContent();
```

```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
  at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
  at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
  at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
  at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
  at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
  at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
  at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
  at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
  at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
  at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
  at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
  at java.net.URLConnection.getContent(URLConnection.java:739)
  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:434)
  at java.net.URL.getContent(URL.java:1052)
  ... 33 elided
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
  at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
  at sun.security.validator.Validator.validate(Validator.java:260)
  at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
  at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
  at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
  at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
  ... 47 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
  at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
  at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
  at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
  ... 53 more

```

Java version 8u45

**Comment by hrj** [comment]
Suprisingly, it works fine in openjdk 7u79.

**Comment by hrj** [comment]
Some Comodo certificates seem to be missing in the trust store. No idea whether they were always missing from the Oracle Java builds. Closing for now.

**Comment by hrj** [comment]
Update: as of Aug 26, it is working fine with Oracle JDK 8u51 as well. Not sure what changed (server or client).

**Comment by champrocks3190** [comment]
I'm having the same problem in 4.4 kitakt but works on marshmallow , tested on both , 

how to overcome this problem ? unsplash api

**Comment by hrj** [comment]
@champrocks3190 it's basically a problem with old runtimes; they won't work out of the box with newer certificates / ciphers. You might have to install new root certificates or ciphers. 

For this project (gngr) the easy solution was to update to latest java, but that is hard to do on an Android. Best place to ask for that is on `stackoverflow.com`.
