### ISSUE TITLE
image encoded in data-uri from ACID2 fails

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#15]
This data URI fails to decode:
```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAFSDNYfAAAAaklEQVR42u3XQQrAIAwAQeP%2F%2F6wf8CJBJTK9lnQ7FpHGaOurt1I34nfH9pMMZAZ8BwMGEvvh%2BBsJCAgICLwIOA8EBAQEBAQEBAQEBK79H5RfIQAAAAAAAAAAAAAAAAAAAAAAAAAAAID%2FABMSqAfj%2FsLmvAAAAABJRU5ErkJggg%3D%3D
```
Exception is:
```
java.lang.IllegalArgumentException: Illegal base64 character 25
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at org.lobobrowser.protocol.data.DataURLConnection.loadHeaderMap(DataURLConnection.java:79)
	at org.lobobrowser.protocol.data.DataURLConnection.<init>(DataURLConnection.java:31)
	at org.lobobrowser.protocol.data.Handler.openConnection(Handler.java:24)
	at java.net.URL.openConnection(URL.java:972)
	at org.lobobrowser.request.RequestEngine.getURLConnection(RequestEngine.java:654)
	at org.lobobrowser.request.RequestEngine.processHandler(RequestEngine.java:760)
	at org.lobobrowser.request.RequestEngine.access$1(RequestEngine.java:744)
	at org.lobobrowser.request.RequestEngine$RequestHandlerTask.lambda$0(RequestEngine.java:1078)
	at org.lobobrowser.request.RequestEngine$RequestHandlerTask$$Lambda$28/1446252515.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lobobrowser.request.RequestEngine$RequestHandlerTask.run(RequestEngine.java:1084)
	at org.lobobrowser.util.SimpleThreadPool$ThreadRunnable.run(SimpleThreadPool.java:129)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hrj** [comment]
[test-case](http://uprootlabs.github.io/gngrTestCases/test-case/i15/)

It seems like other browsers perform a URL decode before doing the Base64 decode. I couldn't find any description of it in the specification, nor in the [errata](https://www.rfc-editor.org/errata_search.php?rfc=2397).

With the URL-Decode step, the test case passes.
