### ISSUE TITLE
Some rare JPGs are not being decoded 

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#152]
They raise this exception:
```
sun.awt.image.ImageFormatException: Unsupported color conversion request
	at sun.awt.image.JPEGImageDecoder.readImage(Native Method)
	at sun.awt.image.JPEGImageDecoder.produceImage(JPEGImageDecoder.java:141)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)
```

Will be uploading a test case soon.

**Comment by hrj** [comment]
Sample image: http://i.imgur.com/OPOFlgc.jpg

This image seems to use a CMYK color space, which is not supported by default in Java. Even `display` from ImageMagick renders it incorrectly.

**Comment by hrj** [comment]
As per [this discussion](https://github.com/radkovo/CSSBox/commit/e44c3c98a120997ac5f253ad38dbbe533fe079a8#commitcomment-14260063) this issue might be solvable by using ImageIO as a fallback.

**Comment by gouessej** [comment]
JOGL JPG decoder probably supports CMYK too.
