### ISSUE TITLE
Can't run in Ubuntu 14.04

### ISSUE THREAD

**Issue by gjedeer** [UprootLabs/gngr#201]
<pre>
➜  ~ /usr/lib/jvm/java-8-oracle/bin/java -jar Download/gngr-0.3.10.jar
java.lang.NoClassDefFoundError: java/net/URLPermission
        at org.lobobrowser.store.StorageManager.<init>(StorageManager.java:76)
        at org.lobobrowser.store.StorageManager.<clinit>(StorageManager.java:66)
        at org.lobobrowser.main.ReuseManager.launch(ReuseManager.java:78)
        at org.lobobrowser.main.EntryPoint.launch(EntryPoint.java:63)
        at org.lobobrowser.main.EntryPoint.lambda$0(EntryPoint.java:79)
        at org.lobobrowser.main.EntryPoint$$Lambda$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.lobobrowser.main.EntryPoint.privilegedLaunch(EntryPoint.java:78)
        at org.lobobrowser.main.EntryPoint.main(EntryPoint.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:491)
        at uno.Uno$3.run(Uno.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at uno.Uno.startMain(Uno.java:193)
        at uno.Uno.main(Uno.java:233)
Caused by: java.lang.ClassNotFoundException: java.net.URLPermission
        at uno.Uno.findClass(Uno.java:110)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 17 more

➜  ~ /usr/lib/jvm/java-8-oracle/bin/java -version                                  
java version "1.8.0-ea"
Java(TM) SE Runtime Environment (build 1.8.0-ea-b108)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b50, mixed mode)
</pre>

**Comment by hrj** [comment]
Hey! Is that the early-access build of java 1.8 ? It's a really old and unstable version; I suggest you try with the latest JRE.

PS: This reminds me, I need to make a new release of gngr soon.

**Comment by gjedeer** [comment]
Thanks for your answer. This is what I've found in the repos. I'll try downloading JRE from Oracle website and if this works, update the wiki.
