### ISSUE TITLE
Java 9 EA 170 compatiblity

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#231]
When running gngr 0.3.12 with Java9 EA 170, the following exception is thrown:

```
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.jdk.internal.reflect")
	at java.base/java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.base/java.security.AccessController.checkPermission(Unknown Source)
	at java.base/java.lang.SecurityManager.checkPermission(Unknown Source)
	at java.base/java.lang.SecurityManager.checkPackageAccess(Unknown Source)
	at java.base/java.lang.ClassLoader$1.run(Unknown Source)
	at java.base/java.lang.ClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.lang.ClassLoader.checkPackageAccess(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at org.lobobrowser.store.StorageManager.getDB(StorageManager.java:93)
	at org.lobobrowser.security.DBRequestRuleStore.<init>(DBRequestRuleStore.java:37)
	at org.lobobrowser.security.DBRequestRuleStore.<clinit>(DBRequestRuleStore.java:29)
```

**Comment by hrj** [comment]
This is no longer reproducible on latest Java LTS (Java 11). It  probably got fixed as part of 065a63bc503129759e1e50d25c57b9f9298e166a
