### ISSUE TITLE
AccessControlException: access denied

### ISSUE THREAD

**Issue by oswetto** [UprootLabs/gngr#238]
Browser: gng 3.1.3
SO: Windows 10
I can't open local html file. 

```
Exception in thread "RequestEngineThreadPool0" java.lang.Error: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Users\user\Desktop\test.html" "read")
	at org.lobobrowser.main.Extension.doWithClassLoader(Extension.java:286)
	at org.lobobrowser.main.Extension.getClientlet(Extension.java:293)
	at org.lobobrowser.main.ExtensionManager.getClientlet(ExtensionManager.java:385)
	at org.lobobrowser.context.CoreClientletSelector.select(CoreClientletSelector.java:31)
	at org.lobobrowser.context.ClientletFactory.getClientlet(ClientletFactory.java:67)
	at org.lobobrowser.request.ClientletRequestHandler.processResponse(ClientletRequestHandler.java:105)
	at org.lobobrowser.request.RequestEngine.processHandler(RequestEngine.java:848)
	at org.lobobrowser.request.RequestEngine.access$1(RequestEngine.java:739)
	at org.lobobrowser.request.RequestEngine$RequestHandlerTask.lambda$0(RequestEngine.java:1076)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lobobrowser.request.RequestEngine$RequestHandlerTask.run(RequestEngine.java:1082)
	at org.lobobrowser.util.SimpleThreadPool$ThreadRunnable.run(SimpleThreadPool.java:129)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by hrj** [comment]
@oswetto Hi! This is intentional. We haven't sealed all access paths in the browser, so we have disabled almost all access to the file-system.

When we want to test local files, we start a quick server with `python -m SimpleHTTPServer` or similar, and browse to `http://localhost:8000`.

**Comment by hrj** [comment]
Closing as works-as-expected.

Thanks for looking @oswetto
