### ISSUE TITLE
startup exception on Mac OS X, class not found: jdk.net.NetworkPermission

### ISSUE THREAD

**Issue by fancyerii** [UprootLabs/gngr#50]
I am using mac os x
/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/bin/java -jar gngr-v0-2-0.jar 
java.lang.NoClassDefFoundError: jdk/net/NetworkPermission
	at org.lobobrowser.store.StorageManager.<init>(StorageManager.java:76)
	at org.lobobrowser.store.StorageManager.<clinit>(StorageManager.java:66)
	at org.lobobrowser.main.ReuseManager.launch(ReuseManager.java:77)
	at org.lobobrowser.main.EntryPoint.launch(EntryPoint.java:63)
	at org.lobobrowser.main.EntryPoint.lambda$0(EntryPoint.java:79)
	at org.lobobrowser.main.EntryPoint$$Lambda$1/834600351.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lobobrowser.main.EntryPoint.privilegedLaunch(EntryPoint.java:78)
	at org.lobobrowser.main.EntryPoint.main(EntryPoint.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at uno.Uno$3.run(Uno.java:200)
	at java.security.AccessController.doPrivileged(Native Method)
	at uno.Uno.startMain(Uno.java:193)
	at uno.Uno.main(Uno.java:233)
Caused by: java.lang.ClassNotFoundException: jdk.net.NetworkPermission
	at uno.Uno.findClass(Uno.java:110)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more

**Comment by hrj** [comment]
Based on [a discussion on Reddit](https://www.reddit.com/r/gngr/comments/2qwxj4/gngr_v02_with_many_layout_improvements/) it seems like the first Java8 release didn't have the required classes.

@fancyerii Please confirm which version of Java you are using, and whether you still face the problem with the latest version.

I am closing this issue for now, but can reopen if more information comes through.

**Comment by adrianN** [comment]
Updating to 1.8.0_25 fixes the SSL problem, as well as the problem with running gngr via java -jar.
